routes/web.php
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'rslt'], function () {
    Route::get('/{token}', [App\Http\Controllers\Pdf\ResultController::class, 'result'])->name('result');
    Route::get('/download/{token}', [App\Http\Controllers\Pdf\ResultController::class, 'downloadByBrowsershot'])->name('download');
});

/** User Route */
Route::group((env('APP_ENV') == 'local' || env('APP_ENV') == 'development' ? ['prefix' => '/'] : ['domain' => 'app.studiorank.xyz']), function () {
    Route::get('login', [App\Http\Controllers\User\AuthController::class, 'login'])->name('user.auth.login');
    Route::post('login', [App\Http\Controllers\User\AuthController::class, 'loginProcess'])->name('user.auth.login-process');
    Route::get('download', [App\Http\Controllers\FileController::class, 'getFile'])->name('user.download');

    /** Public API */
    Route::group(['prefix' => 'api'], function () {
        Route::get('cities', [App\Http\Controllers\User\Api\PublicController::class, 'apiCities'])->name('user.api.cities');
    });

    Route::group(['middleware' => ['auth:user']], function () {
        Route::get('/', [App\Http\Controllers\User\DashboardController::class, 'index'])->name('user.dashboard');
        Route::get('logout', [App\Http\Controllers\User\AuthController::class, 'logout'])->name('user.auth.logout');

        Route::group(['prefix' => 'test', 'middleware' => ['user.complete_data']], function () {
            Route::get('/', [App\Http\Controllers\User\TestController::class, 'index'])->name('user.test.index');

            Route::get('detail/{token}', [App\Http\Controllers\User\TestController::class, 'detail'])->name('user.test.detail');

            Route::group(['middleware' => ['user.test_finished']], function () {
                Route::get('start/{token}', [App\Http\Controllers\User\TestController::class, 'start'])->name('user.test.start');
                Route::post('start/{token}', [App\Http\Controllers\User\TestController::class, 'startProcess'])->name('user.test.start-process');
                Route::get('base/{token}', [App\Http\Controllers\User\TestController::class, 'base'])->name('user.test.base');
                Route::post('base/{token}', [App\Http\Controllers\User\TestController::class, 'baseProcess'])->name('user.test.base-process');
                Route::get('result/{token}', [App\Http\Controllers\User\TestController::class, 'result'])->name('user.test.result');
    
                Route::group(['prefix' => 'question'], function () {
                    Route::get('about/{token}', [App\Http\Controllers\User\Api\TestController::class, 'aboutQuestions'])->name('user.test.about.get');
                    Route::get('get/{token}', [App\Http\Controllers\User\Api\TestController::class, 'getQuestions'])->name('user.test.question.get');
                    Route::post('answer/{token}', [App\Http\Controllers\User\Api\TestController::class, 'saveAnswer'])->name('user.test.question.answer');
                    Route::post('misbehavior-window/{token}', [App\Http\Controllers\User\Api\TestController::class, 'misbehaviorWindow'])->name('user.test.question.misbehavior-window');
                });
            });
        });

        Route::group(['prefix' => 'setting'], function () {
            Route::get('profile', [App\Http\Controllers\User\SettingController::class, 'profile'])->name('user.setting.profile');
            Route::post('profile', [App\Http\Controllers\User\SettingController::class, 'profileProcess'])->name('user.setting.profile-process');
        });
    });
});

/** Company Route */
Route::group((env('APP_ENV') == 'local' || env('APP_ENV') == 'development' ? ['prefix' => 'company'] : ['domain' => 'admin.studiorank.xyz']), function () {

    /** Download File */    
    Route::get('/', [App\Http\Controllers\Company\DashboardController::class, 'index'])->name('company.home')->middleware('auth:company');
    Route::get('login', [App\Http\Controllers\Company\AuthController::class, 'login'])->name('company.auth.login');
    Route::post('login', [App\Http\Controllers\Company\AuthController::class, 'loginProcess'])->name('company.auth.login-process');

    Route::group(['middleware' => ['auth:company']], function () {
        Route::get('dashboard', [App\Http\Controllers\Company\DashboardController::class, 'index'])->name('company.dashboard');
        Route::get('logout', [App\Http\Controllers\Company\AuthController::class, 'logout'])->name('company.auth.logout');
        Route::get('download', [App\Http\Controllers\FileController::class, 'getFile'])->name('company.download');

        Route::group(['prefix' => 'test'], function () {
            Route::get('/', [App\Http\Controllers\Company\TestController::class, 'index'])->name('company.test.index');
            Route::get('{id}/detail', [App\Http\Controllers\Company\TestController::class, 'show'])->name('company.test.show');
            Route::get('create', [App\Http\Controllers\Company\TestController::class, 'create'])->name('company.test.create');
            Route::post('create', [App\Http\Controllers\Company\TestController::class, 'store'])->name('company.test.store');
            Route::get('{id}/edit', [App\Http\Controllers\Company\TestController::class, 'edit'])->name('company.test.edit');
            Route::post('{id}/edit', [App\Http\Controllers\Company\TestController::class, 'update'])->name('company.test.update');

            Route::group(['prefix' => 'invitation'], function () {
                Route::get('{id}/create', [App\Http\Controllers\Company\InvititationParticipantController::class, 'createSingle'])->name('company.test.invititation.create');
                Route::post('{id}/create', [App\Http\Controllers\Company\InvititationParticipantController::class, 'storeSingle'])->name('company.test.invititation.store');
                Route::get('{id}/create-multiple', [App\Http\Controllers\Company\InvititationParticipantController::class, 'createMultiple'])->name('company.test.invititation.create-multiple');
                Route::post('{id}/create-multiple', [App\Http\Controllers\Company\InvititationParticipantController::class, 'storeMultiple'])->name('company.test.invititation.store-multiple');
            });
        });

        Route::group(['prefix' => 'module'], function () {
            Route::get('/', [App\Http\Controllers\Company\ModuleController::class, 'index'])->name('company.module.index');
            Route::get('{id}/detail', [App\Http\Controllers\Company\ModuleController::class, 'show'])->name('company.module.show');
            Route::get('create', [App\Http\Controllers\Company\ModuleController::class, 'create'])->name('company.module.create');
            Route::post('store', [App\Http\Controllers\Company\ModuleController::class, 'store'])->name('company.module.store');
            Route::post('edit/{id}', [App\Http\Controllers\Company\ModuleController::class, 'update'])->name('company.module.update');
            Route::get('delete/{id}', [App\Http\Controllers\Company\ModuleController::class, 'destroy'])->name('company.module.destroy');

            Route::group(['prefix' => 'question'], function () {
                Route::get('create/{id}', [App\Http\Controllers\Company\QuestionController::class, 'createSingle'])->name('company.module.question.create');
                Route::post('store/{id}', [App\Http\Controllers\Company\QuestionController::class, 'storeSingle'])->name('company.module.question.store');
                Route::get('create-multiple/{id}', [App\Http\Controllers\Company\QuestionController::class, 'createMultiple'])->name('company.module.question.create-multiple');
                Route::post('create-multiple/{id}', [App\Http\Controllers\Company\QuestionController::class, 'storeMultiple'])->name('company.module.question.store-multiple');
                Route::get('edit/{id}', [App\Http\Controllers\Company\QuestionController::class, 'edit'])->name('company.module.question.edit');
                Route::post('edit/{id}', [App\Http\Controllers\Company\QuestionController::class, 'update'])->name('company.module.question.update');
                Route::get('delete/{id}', [App\Http\Controllers\Company\QuestionController::class, 'destroy'])->name('company.module.question.destroy');
            });
        });

        Route::group(['prefix' => 'grade'], function () {
            Route::get('/', [App\Http\Controllers\Company\GradeController::class, 'index'])->name('company.grade.index');
            Route::get('create', [App\Http\Controllers\Company\GradeController::class, 'create'])->name('company.grade.create');
            Route::post('create', [App\Http\Controllers\Company\GradeController::class, 'store'])->name('company.grade.store');
            Route::get('edit/{id}', [App\Http\Controllers\Company\GradeController::class, 'edit'])->name('company.grade.edit');
            Route::post('edit/{id}', [App\Http\Controllers\Company\GradeController::class, 'update'])->name('company.grade.update');
            Route::get('delete/{id}', [App\Http\Controllers\Company\GradeController::class, 'destroy'])->name('company.grade.destroy');
        });

        Route::group(['prefix' => 'setting'], function () {
            Route::get('account', [App\Http\Controllers\Company\SettingController::class, 'account'])->name('company.setting.account');
            Route::post('account', [App\Http\Controllers\Company\SettingController::class, 'accountUpdate'])->name('company.setting.account-update');
            Route::post('password', [App\Http\Controllers\Company\SettingController::class, 'passwordUpdate'])->name('company.setting.password-update');
            Route::get('company', [App\Http\Controllers\Company\SettingController::class, 'company'])->name('company.setting.company');

app/Models/ModuleQuestion.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ModuleQuestion extends Model
{
    use HasFactory;

    protected $table = 'module_questions';

    public $fillable = [
        'question',
        'question_image',
        'question_image_type',
        'choices',
        'answer',
        'point_plus',
        'point_min',
        'category_id',
        'module_id',
        'company_id',
        'created_by'
    ];

    public function module()
    {
        return $this->belongsTo(Module::class);
    }

    public function category()
    {
        return $this->belongsTo(ModuleQuestionCategory::class, 'category_id');
    }

    public function scopeByCompany($query)
    {
        $query->where('company_id', auth()->id());
    }

    public function scopeByModule($query, $value)
    {
        $query->where('module_id', $value);
    }

    public function getShowImageAttribute()
    {
        if ($this->attributes['question_image'] && $this->attributes['question_image_type']) {
            // Convert bytea to string from question_image
            
            $image = 'data:'.$this->attributes['question_image_type'].';base64,'.$this->attributes['question_image'];
        } else {
            $image = null;
        }
        return $image;
    }
}

app/Http/Controllers/Company/AuthController.php
<?php

namespace App\Http\Controllers\Company;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class AuthController extends Controller
{
    public function login()
    {
        return view('company.auth.login');
    }

    public function loginProcess(Request $request)
    {
        $this->validate($request, [
            'email' => 'required|email',
            'password' => 'required',
        ]);

        $credentials = $request->only('email', 'password');

        if (auth()->guard('company')->attempt($credentials)) {
            return redirect()->route('company.dashboard');
        }

        return redirect()->back()->withErrors([
            'email' => 'Email atau password salah',
        ]);
    }

    public function logout()
    {
        auth()->guard('company')->logout();

        return redirect()->route('company.auth.login');
    }
}

app/Http/Controllers/Company/DashboardController.php
<?php

namespace App\Http\Controllers\Company;

use App\Http\Controllers\Controller;
use App\Models\Test;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index()
    {
        $tests = Test::byCompany()->get();
        $notWorkingTest = Test::byCompany()->whereHas('participants', function ($query) {
            $query->where('status', '1');
        })->get();
        $onGoingTest = Test::byCompany()->whereHas('participants', function ($query) {
            $query->where('status', '2');
        })->get();
        $doneTest = Test::byCompany()->whereHas('participants', function ($query) {
            $query->where('status', '3');
        })->get();

        return view('company.dashboard', [
            'tests' => $tests,
            'notWorkingTest' => $notWorkingTest,
            'onGoingTest' => $onGoingTest,
            'doneTest' => $doneTest,
        ]);
    }
}

app/Http/Controllers/Company/GradeController.php
<?php

namespace App\Http\Controllers\Company;

use App\Http\Controllers\Controller;
use App\Models\Grade;
use App\Models\GradeGroup;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class GradeController extends Controller
{
    public function attributes()
    {
        return [
            'group' => 'Nama Group',
            'name' => 'Tampilan Peringkat',
            'value_start' => 'Nilai Awal',
            'value_end' => 'Nilai Akhir',
            'result' => 'Hasil Peringkat',
            'color' => 'Warna Peringkat'
        ];
    }

    public function index()
    {
        $grades = Grade::byCompany()->get();

        return view('company.grade.index', [
            'grades' => $grades
        ]);
    }

    public function create()
    {
        $groups = GradeGroup::byCompany()->get();
        return view('company.grade.create', [
            'groups' => $groups
        ]);
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'group' => 'required',
            'name' => 'required',
            'value_start' => 'required|numeric|lt:value_end',
            'value_end' => 'required|numeric|gt:value_start',
            'result' => 'required',
            'color' => 'required|in:red,yellow,orange,green,blue'
        ], [], $this->attributes());
        
        DB::beginTransaction();
        try {
            $group = GradeGroup::firstOrCreate([
                'name' => json_decode($request->group)[0]->value,
                'company_id' => auth()->guard('company')->user()->company_id
            ], [
                'created_by' => auth()->guard('company')->user()->id
            ]);

            $grade = new Grade();
            $grade->group_id = $group->id;
            $grade->value_start = $request->value_start;
            $grade->value_end = $request->value_end;
            $grade->name = $request->name;
            $grade->result = $request->result;
            $grade->color = $request->color;
            $grade->created_by = auth()->guard('company')->id();
            $grade->company_id = auth()->guard('company')->user()->company_id;
            $grade->save();

            DB::commit();
            return redirect()->route('company.grade.index')->with('success', 'Berhasil menambahkan data peringkat');
        } catch (\Throwable $th) {
            DB::rollback();
            dd($th->getMessage());
            return redirect()->back()->with('error', 'Gagal menambahkan data peringkat');
        }
    }

    public function edit($id)
    {
        $grade = Grade::byCompany()->findOrFail($id);
        $groups = GradeGroup::byCompany()->get();
        return view('company.grade.edit', [
            'grade' => $grade,
            'groups' => $groups
        ]);
    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'group' => 'required',
            'name' => 'required',
            'value_start' => 'required|numeric|lt:value_end',
            'value_end' => 'required|numeric|gt:value_start',
            'result' => 'required',
            'color' => 'required|in:red,yellow,orange,green,blue'
        ], [], $this->attributes());
        
        DB::beginTransaction();
        try {
            $group = GradeGroup::firstOrCreate([
                'name' => json_decode($request->group)[0]->value,
                'company_id' => auth()->guard('company')->user()->company_id
            ], [
                'created_by' => auth()->guard('company')->user()->id
            ]);

            $grade = Grade::byCompany()->findOrFail($id);
            $grade->group_id = $group->id;
            $grade->value_start = $request->value_start;
            $grade->value_end = $request->value_end;
            $grade->name = $request->name;
            $grade->result = $request->result;
            $grade->color = $request->color;
            $grade->save();

            DB::commit();
            return redirect()->route('company.grade.index')->with('success', 'Berhasil mengubah data peringkat');
        } catch (\Throwable $th) {
            DB::rollback();
            dd($th->getMessage(), $request->all());
            return redirect()->back()->with('error', 'Gagal mengubah data peringkat');
        }
    }

    public function destroy($id)
    {
        $grade = Grade::byCompany()->findOrFail($id);
        $grade->delete();

        return redirect()->route('company.grade.index')->with('success', 'Berhasil menghapus data peringkat');
    }
}

resources/views/company/module/index.blade.php
@extends('layouts.appCompany')

@section('content')
<div class="row">
    <div class="col-lg-12">
        <div class="card border">
            <div class="card-header">
                <div class="card-title">
                    <h4>Daftar Modul</h4>
                </div>
                <div class="card-title">
                    <a href="{{ Route('company.module.create') }}" class="btn btn-primary btn-sm">
                        <i class="fa fa-plus"></i>
                        Tambah Modul
                    </a>
                </div>
            </div>
            <div class="card-body py-0">
                <table class="table align-middle table-row-dashed datatable gy-4">
                    <thead>
                        <tr class="fw-bold fs-6 text-gray-800">
                            <th class="min-w-150px">Tipe Modul</th>
                            <th class="min-w-150px">Nama Modul</th>
                            <th class="min-w-150px">Tampilan Peringkat</th>
                            <th class="min-w-200px">Status Menampilkan</th>
                            <th class="min-w-100px"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($modules as $module)
                        <tr>
                            <td>
                                @if($module->type == 'test')
                                    Test Assessment
                                @elseif($module->type == 'psychotest')
                                    Psikotest
                                @endif
                            </td>
                            <td>{{ $module->name }}</td>
                            <td>{{ $module->groupGrade->name }}</td>
                            <td>
                                @if($module->is_publish)
                                    <span class="badge badge-success">Ditampilkan</span>
                                @else
                                    <span class="badge badge-danger">Tidak Ditampilkan</span>
                                @endif   
                            </td>
                            <td>
                                <div class="d-flex justify-content-end flex-shrink-0">
                                    <a href="{{ Route('company.module.show', $module->id) }}" class="btn btn-bg-light btn-color-muted btn-active-color-primary btn-sm px-4 me-2">
                                        <i class="bi bi-eye"></i> Lihat
                                    </a>
                                    <button class="btn btn-bg-light btn-color-muted btn-active-color-primary btn-sm px-4 me-2" onclick="openModalDelete('{{ Route('company.module.destroy', $module->id) }}')">
                                        <i class="bi bi-trash"></i> Hapus
                                    </button>
                                </div>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/company/module/show.blade.php
@extends('layouts.appCompany')

@section('content')
<div class="modal fade" tabindex="-1" id="editModul">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title">Edit Modul</h3>
            </div>
            <div class="modal-body">
                <form id="formUpdateModule" method="POST" action="{{ Route('company.module.update', $module->id) }}">
                    @csrf
                    <div class="mb-10 fv-row">
                        <label class="required form-label">Nama Modul</label>
                        <input type="text" class="form-control form-control-sm @error('name') is-invalid @enderror" name="name" placeholder="Nama Modul" value="{{ $module->name }}" autocomplete="off">
                        @error('name')
                        <div class="invalid-feedback">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="mb-10 fv-row">
                        <label class="form-label">Keterangan</label>
                        <textarea class="form-control form-control-sm @error('description') is-invalid @enderror" name="description" placeholder="Keterangan">{{ $module->description }}</textarea>
                        @error('description')
                        <div class="invalid-feedback">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="mb-10 fv-row">
                        <label class="required form-label">Tampilan Peringkat</label>
                        <select class="form-select form-select-sm @error('grade') is-invalid @enderror" name="grade" data-control="select2" data-hide-search="true" data-placeholder="Pilih Tampilan Peringkat">
                            <option value=""></option>
                            @foreach ($gradesGroup as $grade)
                            <option value="{{ $grade->id }}" {{ $module->grade_group_id == $grade->id ? 'selected' : '' }}>{{ $grade->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="mb-10 fv-row">
                        <label class="required form-label">Status Menampilkan</label>
                        <select class="form-select form-select-sm @error('is_publish') is-invalid @enderror" name="is_publish" data-control="select2" data-hide-search="true" data-placeholder="Pilih Status Menampilkan">
                            <option value="" disabled selected></option>
                            <option value="1" {{ isset($module->is_publish) && $module->is_publish == 1 ? 'selected' : '' }}>Tampilkan</option>
                            <option value="0" {{ isset($module->is_publish) && $module->is_publish == 0 ? 'selected' : '' }}>Jangan Ditampilkan</option>
                        </select>
                        @error('is_publish')
                        <div class="invalid-feedback">{{ $message }}</div>
                        @enderror
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-light btn-sm" data-bs-dizsmiss="modal">Batalkan</button>
                <button type="submit" class="btn btn-primary btn-sm" form="formUpdateModule">Simpan Perubahan</button>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="row">
            <div class="col-lg-12 mb-7">
                <div class="card border">
                    <div class="card-header">
                        <div class="card-title">
                            <h4>Detail Modul</h4>
                        </div>
                        <div class="card-title">
                            <button class="btn btn-secondary btn-sm" data-bs-toggle="modal" data-bs-target="#editModul">
                                <i class="fa fa-pen"></i>
                                Edit Modul
                            </button>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="row mb-7">
                            <label class="col-lg-2 fw-semibold">Tipe Modul</label>
                            <div class="col-lg-8">
                                <span class="fw-bold text-gray-800">
                                    @if($module->type == 'test')
                                        Test Assessment
                                    @elseif($module->type == 'psychotest')
                                        Psikotest
                                    @endif
                                </span>
                            </div>
                        </div>
                        <div class="row mb-7">
                            <label class="col-lg-2 fw-semibold">Nama Modul</label>
                            <div class="col-lg-8">
                                <span class="fw-bold text-gray-800">{{ $module->name }}</span>
                            </div>
                        </div>
                        <div class="row mb-7">
                            <label class="col-lg-2 fw-semibold">Keterangan</label>
                            <div class="col-lg-8">
                                <span class="fw-bold fs-6 text-gray-800">{{ $module->description }}</span>
                            </div>
                        </div>
                        <div class="row mb-7">
                            <label class="col-lg-2 fw-semibold">Tampilan Peringkat</label>
                            <div class="col-lg-8">
                                <span class="fw-bold fs-6 text-gray-800">{{ $module->groupGrade->name }}</span>
                            </div>
                        </div>
                        <div class="row mb-7">
                            <label class="col-lg-2 fw-semibold">Status Menampilkan</label>
                            <div class="col-lg-8">
                                @if($module->is_publish)
                                    <span class="badge badge-success">Ditampilkan</span>
                                @else
                                    <span class="badge badge-danger">Tidak Ditampilkan</span>
                                @endif
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-12 mb-7">
        <div class="card border">
            <div class="card-header">
                <div class="card-title">
                    <h4>Daftar Soal</h4>
                </div>
                <div class="card-title">
                    <a href="javascript::void();" class="btn btn-success btn-sm" data-kt-menu-trigger="click" data-kt-menu-placement="top-start">
                        <i class="fa fa-plus"></i>
                        Tambah Soal
                    </a>
                    <div class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-600 menu-state-bg-light-primary fw-bold fs-7 w-300px py-4" data-kt-menu="true">
                        <div class="menu-item px-3">
                            <a href="{{ Route('company.module.question.create', $module->id) }}" class="menu-link">
                                <i class="menu-icon fa-solid fa-plus"></i>
                                Tambah Satu Soal
                            </a>
                        </div>
                        <div class="menu-item px-3">
                            <a href="{{ Route('company.module.question.create-multiple', $module->id) }}" class="menu-link">
                                <i class="menu-icon fa-solid fa-upload"></i>
                                Tambah Banyak Soal
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-body py-0">
                <table class="table align-middle table-row-dashed datatable gy-4">
                    <thead>
                        <tr class="fw-bold fs-6 text-gray-800">
                            <th class="min-w-50px">No</th>
                            <th class="min-w-150px">Gambar Soal</th>
                            <th class="min-w-400px">Soal</th>
                            <th class="min-w-600px">Pilihan Ganda</th>
                            <th class="min-w-50px">Jawaban</th>
                            <th class="min-w-200px"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($module->questions->sortByDesc('created_at') as $question)
                        <tr>
                            <td class="text-center">{{ $loop->iteration }}</td>
                            <td class="text-center">
                                @if ($question->show_image)
                                <img src="{{ $question->show_image }}" class="img-fluid" width="55px">
                                @else
                                -
                                @endif
                            </td>
                            <td>{!! nl2br($question->question) !!}</td>
                            <td>
                                <ul type="A">
                                @foreach(json_decode($question->choices) as $choice)
                                    <li>{!! nl2br($choice) !!}</li>
                                @endforeach
                                </ul>
                            </td>
                            <td class="fw-bold text-center">{{ $question->answer }}</td>
                            <td>
                                <div class="d-flex justify-content-end flex-shrink-0">
                                    <a href="{{ Route('company.module.question.edit', $question->id) }}" class="btn btn-bg-light btn-color-muted btn-active-color-primary btn-sm px-4 me-2">
                                        <i class="bi bi-pencil"></i> Edit
                                    </a>
                                    <button class="btn btn-bg-light btn-color-muted btn-active-color-primary btn-sm px-4 me-2" onclick="openModalDelete('{{ Route('company.module.question.destroy', $question->id) }}')">
                                        <i class="bi bi-trash"></i> Hapus
                                    </button>
                                </div>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection